# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches: [ "main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-portal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Deploy Portal API Address
        uses: docker/build-push-action@v4
        with:
          context: portal/api-address
          tags: paulahage/api-address:main
          push: true
      - name: Build and Deploy Portal API Plans
        uses: docker/build-push-action@v4
        with:
          context: portal/api-data-plans
          tags: paulahage/api-data-plans:main
          push: true
      - name: Build Portal Website
        working-directory: portal/website
        run: npm ci && npm run build
      - name: Deploy Portal Website
        uses: docker/build-push-action@v4
        with:
          context: portal/website
          tags: paulahage/portal-website:main
          push: true
      - name: Build Shop UI
        working-directory: shop/ui
        run: npm ci && npm run build
      - name: Deploy Shop UI
        uses: docker/build-push-action@v4
        with:
          context: shop/ui
          tags: paulahage/shop-ui:main
          push: true
      - name: deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASS }}
          script: |
            cd ~/apps
            docker compose pull
            docker compose up -d
